version: '3'

services:
  mysql-db:
    container_name: mysql-db
    image: mysql:5.7
    # image: mysql:8.0
    ports:
      - 3306:3306
    build:
      context: .
      args:
      - LANG=zh_CN.UTF-8
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ALLOW_Empty_PASSWORD: no

      # 自动创建名为 'bluebell' 的数据库，create database bluebell;
      MYSQL_DATABASE: bluebell
      # 自动创建数据库的普通用户 'test'
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456
      
    volumes:
      # 数据挂载
      # - ./mysql/data:/var/lib/mysql      
      - /home/xsj/go/src/github.com/sjxiang/dev_script/temp02/mysql:/var/lib/mysql   

    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci



  redis-cache:
    container_name: redis-cache
    image: redis:latest
    ports: 
      - "6379:6379"
    volumes:
      - /home/xsj/go/src/github.com/sjxiang/dev_script/temp02/redis/data:/data
    command: redis-server --appendonly yes 
    
